# Generated by Django 5.2.14 on 2026-05-19 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "issuer",
                    models.CharField(
                        help_text="Issuing body (e.g. 'NCC Tanzania', 'ISO').", max_length=200
                    ),
                ),
                ("year_awarded", models.PositiveIntegerField()),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional scan / logo of the certificate.",
                        upload_to="construction/certifications/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["order", "-year_awarded"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line pitch shown on service cards.", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full description for the service detail section.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Material Symbols icon name (e.g. 'engineering', 'apartment').",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Construction Service",
                "verbose_name_plural": "Construction Services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("civil", "Civil Works"),
                            ("industrial", "Industrial"),
                            ("fitout", "Interior Fit-out"),
                            ("renovation", "Renovation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_city", models.CharField(max_length=100)),
                ("location_region", models.CharField(blank=True, default="", max_length=100)),
                ("year_completed", models.PositiveIntegerField()),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Project narrative shown on the detail page.",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Hero image for the project card and detail page. 16:9 looks best.",
                        upload_to="construction/projects/",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured projects appear in the homepage 'Featured Projects' strip.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-year_completed", "title"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(max_length=200)),
                (
                    "author_role",
                    models.CharField(
                        blank=True, default="", help_text="e.g. 'Managing Director'", max_length=200
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client company / institution name.",
                        max_length=200,
                    ),
                ),
                ("quote", models.TextField(help_text="The client's testimonial text.")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured testimonials surface on the homepage."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
