# Generated by Django 5.2.14 on 2026-05-19 14:15

import apps.construction.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("civil", "Civil Works"),
                            ("industrial", "Industrial"),
                            ("fitout", "Interior Fit-out"),
                            ("renovation", "Renovation"),
                        ],
                        help_text="Sector classification for the requested project.",
                        max_length=20,
                    ),
                ),
                ("location_region", models.CharField(max_length=100)),
                ("location_district", models.CharField(blank=True, default="", max_length=100)),
                (
                    "estimated_start",
                    models.DateField(
                        blank=True,
                        help_text="Approximate start date the client has in mind.",
                        null=True,
                    ),
                ),
                (
                    "scope_description",
                    models.TextField(
                        help_text="Free-text scope description (minimum 50 characters)."
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_50m", "Under 50M TZS"),
                            ("50m_200m", "50M – 200M TZS"),
                            ("200m_1b", "200M – 1B TZS"),
                            ("over_1b", "Over 1B TZS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("1_3", "1 – 3 months"),
                            ("3_6", "3 – 6 months"),
                            ("6_12", "6 – 12 months"),
                            ("over_12", "12+ months"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin-only notes — not visible to the client.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="construction/quote_attachments/%Y/%m/",
                        validators=[apps.construction.models._validate_attachment],
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="construction.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Attachment",
                "verbose_name_plural": "Quote Attachments",
                "ordering": ["created_at"],
            },
        ),
    ]
