# Generated by Django 5.2.14 on 2026-05-21 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Registration / licence name (e.g. 'TBS Food Safety Mark').",
                        max_length=200,
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        help_text="Issuing body (e.g. 'Tanzania Bureau of Standards').",
                        max_length=200,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Public registration / licence number, if any.",
                        max_length=100,
                    ),
                ),
                ("year_awarded", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional scan / logo of the certificate.",
                        upload_to="farming/certifications/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Certification / Registration",
                "verbose_name_plural": "Certifications / Registrations",
                "ordering": ["order", "-year_awarded"],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "region",
                    models.CharField(
                        help_text="Tanzanian region the farm sits in (e.g. 'Mbeya', 'Pwani').",
                        max_length=100,
                    ),
                ),
                (
                    "size_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approximate land size in hectares (leave blank if not disclosed).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "primary_activity",
                    models.CharField(
                        choices=[
                            ("crops", "Crops"),
                            ("poultry", "Poultry"),
                            ("processed", "Processed Goods"),
                        ],
                        help_text="What this farm mainly produces.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Narrative shown on the /farming/farms/ page card.",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Cover photo for the farm card. 16:9 looks best.",
                        upload_to="farming/farms/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FarmingProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("crops", "Crops"),
                            ("poultry", "Poultry"),
                            ("processed", "Processed Goods"),
                        ],
                        help_text="Groups products on the /farming/products/ page.",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line pitch shown on product cards.", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full description for the product detail section.",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram (kg)"),
                            ("dozen", "Dozen (eg. eggs)"),
                            ("each", "Each (per bird)"),
                            ("litre", "Litre"),
                            ("bag", "Bag (50 kg)"),
                        ],
                        default="kg",
                        help_text="Default selling unit — inform buyers without quoting a price.",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional product photo. Square crop reads best on cards.",
                        upload_to="farming/products/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured products appear on the homepage strip."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Farming Product",
                "verbose_name_plural": "Farming Products",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrderInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("organisation", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("wholesale", "Wholesale Buyer"),
                            ("retail", "Retail Customer"),
                            ("partnership", "Partnership / Contract Farming"),
                        ],
                        default="wholesale",
                        max_length=20,
                    ),
                ),
                (
                    "products_of_interest",
                    models.TextField(
                        help_text="Free-text list of products the buyer wants (kept simple — not M2M so partial / mistyped names still capture the lead)."
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Approximate quantity / volume (e.g. '500 kg', '20 trays', '2 tonnes / month'). Free-text — units vary by product.",
                        max_length=200,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_off", "One-off Order"),
                            ("monthly", "Monthly / Recurring"),
                            ("seasonal", "Seasonal"),
                        ],
                        default="one_off",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Region / city where the buyer wants delivery (optional).",
                        max_length=200,
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Free-text notes from the buyer."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("fulfilled", "Fulfilled"),
                            ("declined", "Declined"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin-only notes — not visible to the buyer.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Inquiry",
                "verbose_name_plural": "Order Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(max_length=200)),
                (
                    "author_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Procurement Manager'",
                        max_length=200,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Buyer / partner / cooperative name.",
                        max_length=200,
                    ),
                ),
                ("quote", models.TextField(help_text="The customer's testimonial text.")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured testimonials surface on the homepage."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
