# Generated by Django 5.2.14 on 2026-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_body",
            field=models.TextField(
                blank=True,
                default="As a trusted corporate partner, we specialize in delivering strategic solutions, combining business insight and innovation to drive results.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_headline",
            field=models.CharField(
                blank=True, default="We Turn Vision Into Reality", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_video_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="clients_count",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_body",
            field=models.CharField(
                blank=True,
                default="Let's discuss how we can help you achieve your business goals.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_headline",
            field=models.CharField(
                blank=True, default="Ready To Take Your Business Further?", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_text",
            field=models.CharField(blank=True, default="View Our Services", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_headline",
            field=models.CharField(
                blank=True, default="Empowering Tanzania With Business Excellence", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subheadline",
            field=models.CharField(
                blank=True,
                default="Building scalable, high-impact solutions to help you grow with confidence.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission",
            field=models.TextField(
                blank=True,
                default="To empower Tanzanian businesses through diversified, innovative, and sustainable solutions.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="projects_count",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="satisfaction_pct",
            field=models.PositiveIntegerField(default=98),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision",
            field=models.TextField(
                blank=True,
                default="To be Tanzania's most trusted and impactful group of companies.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="years_experience",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
