# Generated by Django 5.2.14 on 2026-05-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_about_body_sitesettings_about_headline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSettings",
            fields=[],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Section",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="ContactSettings",
            fields=[],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="CTASettings",
            fields=[],
            options={
                "verbose_name": "CTA Section",
                "verbose_name_plural": "CTA Section",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="HeroSettings",
            fields=[],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="IdentitySettings",
            fields=[],
            options={
                "verbose_name": "Identity & Branding",
                "verbose_name_plural": "Identity & Branding",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="MissionVisionSettings",
            fields=[],
            options={
                "verbose_name": "Mission & Vision",
                "verbose_name_plural": "Mission & Vision",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
    ]
