# Generated by Django 5.2.14 on 2026-05-11 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertical', models.CharField(choices=[('financial', 'Financial Services'), ('construction', 'Construction'), ('energies', 'Energies'), ('farming', 'Farming'), ('investments', 'Investments')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerticalPlaceholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertical', models.CharField(choices=[('financial', 'Financial Services'), ('construction', 'Construction'), ('energies', 'Energies'), ('farming', 'Farming'), ('investments', 'Investments')], max_length=50, unique=True)),
                ('headline', models.CharField(blank=True, default='', max_length=300)),
                ('subheadline', models.CharField(blank=True, default='', max_length=500)),
                ('primary_color', models.CharField(default='#1a1a2e', max_length=7)),
                ('accent_color', models.CharField(default='#e94560', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vertical Placeholder',
                'verbose_name_plural': 'Vertical Placeholders',
            },
        ),
    ]
