# Generated by Django 5.2.14 on 2026-05-20 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Registration / licence name (e.g. 'BoT Agency Banking Registration').",
                        max_length=200,
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        help_text="Issuing body (e.g. 'Bank of Tanzania', 'BRELA').", max_length=200
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Public registration / licence number, if any.",
                        max_length=100,
                    ),
                ),
                ("year_awarded", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional scan / logo of the certificate.",
                        upload_to="financial/certifications/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Certification / Registration",
                "verbose_name_plural": "Certifications / Registrations",
                "ordering": ["order", "-year_awarded"],
            },
        ),
        migrations.CreateModel(
            name="FinancialService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("loans", "Microfinance & Lending"),
                            ("investments", "Investments & Partnerships"),
                            ("agency", "Agency & Franchising"),
                            ("securities", "Government Securities & DSE"),
                            ("auto", "Auto & Asset Services"),
                        ],
                        help_text="Groups services on the /financial/services/ page.",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One-line pitch shown on service cards.", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full description for the service detail section.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Material Symbols icon name (e.g. 'savings', 'account_balance').",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Financial Service",
                "verbose_name_plural": "Financial Services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Public reference (e.g. 'BFS/IO/2026/01').",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "tenure_months",
                    models.PositiveIntegerField(help_text="Tenure in months (e.g. 12, 24)."),
                ),
                (
                    "indicative_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Indicative annual rate, e.g. 16.50 for 16.5%.",
                        max_digits=5,
                    ),
                ),
                (
                    "min_capital",
                    models.DecimalField(
                        decimal_places=2, help_text="Minimum capital in TZS.", max_digits=12
                    ),
                ),
                (
                    "payout_cadence",
                    models.CharField(
                        choices=[
                            ("quarterly", "Quarterly (every 3 months)"),
                            ("semi_annual", "Semi-annual"),
                            ("annual", "Annual"),
                            ("maturity", "At maturity"),
                        ],
                        default="quarterly",
                        max_length=20,
                    ),
                ),
                ("opens_at", models.DateField(blank=True, null=True)),
                ("closes_at", models.DateField(blank=True, null=True)),
                (
                    "settlement_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the principal is returned to the investor.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("upcoming", "Upcoming"), ("open", "Open"), ("closed", "Closed")],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Narrative description shown on the offering detail page.",
                    ),
                ),
                (
                    "payout_calendar_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text calendar / dates table content (interest payment schedule).",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured offerings appear on the homepage."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Investment Offering",
                "verbose_name_plural": "Investment Offerings",
                "ordering": ["order", "-opens_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("business_name", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "loan_purpose",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("sme", "SME / Business"),
                            ("group", "Group Loan"),
                            ("asset", "Asset Finance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2, help_text="Requested amount in TZS.", max_digits=12
                    ),
                ),
                (
                    "tenure_band",
                    models.CharField(
                        choices=[
                            ("under_6", "Under 6 months"),
                            ("6_12", "6 – 12 months"),
                            ("12_24", "1 – 2 years"),
                            ("over_24", "2+ years"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Free-text notes from the applicant."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("declined", "Declined"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin-only notes — not visible to the applicant.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Inquiry",
                "verbose_name_plural": "Loan Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(max_length=200)),
                (
                    "author_role",
                    models.CharField(
                        blank=True, default="", help_text="e.g. 'Managing Director'", max_length=200
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client company / organisation name.",
                        max_length=200,
                    ),
                ),
                ("quote", models.TextField(help_text="The client's testimonial text.")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured testimonials surface on the homepage."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "capital_band",
                    models.CharField(
                        choices=[
                            ("250k_1m", "TZS 250,000 – 1,000,000"),
                            ("1m_5m", "TZS 1,000,000 – 5,000,000"),
                            ("5m_10m", "TZS 5,000,000 – 10,000,000"),
                            ("over_10m", "TZS 10,000,000+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_tenure",
                    models.CharField(
                        choices=[
                            ("1yr", "1 Year (BFS/IO/2026/01)"),
                            ("2yr", "2 Years (BFS/IO/2026/02)"),
                            ("undecided", "Undecided / Discuss"),
                        ],
                        default="undecided",
                        max_length=20,
                    ),
                ),
                (
                    "funding_source",
                    models.CharField(
                        choices=[
                            ("savings", "Personal Savings"),
                            ("business", "Business Profits"),
                            ("sale", "Sale of Asset"),
                            ("other", "Other"),
                        ],
                        default="savings",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Free-text notes from the prospect."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("committed", "Committed"),
                            ("funded", "Funded"),
                            ("active", "Active"),
                            ("matured", "Matured"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin-only notes — not visible to the prospect.",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific offering the prospect referenced (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="financial.investmentoffering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Inquiry",
                "verbose_name_plural": "Investment Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
